import type {
  CodexSessionMessage,
  CodexSessionMeta,
  CodexPromptEntry,
  CodexSkillEntry,
  CloseBehavior,
  ProfilesSnapshotResponse,
  QuotaSummary,
  ShellRoute,
  SwitchRestartTargets,
  UsageQuerySettings,
  UsageStatsRangePreset,
  UsageStatsRefreshSeconds,
  UsageStatsResponse,
} from "@front-shared/types";
import type { Locale } from "@front-shared/i18n";
import type { ThemeId } from "@front-shared/theme";
import {
  resolveInitialShowAccountDetail,
  resolveInitialCloseBehavior,
  resolveInitialSwitchRestartTargets,
  resolveInitialUsageStatsCustomRange,
  resolveInitialUsageStatsRange,
  resolveInitialUsageStatsRefreshSeconds,
} from "@front-shared/preferences";

const initialUsageStatsCustomRange = resolveInitialUsageStatsCustomRange();

export const state = {
  page: 1,
  loading: false,
  refreshActiveProfiles: [] as string[],
  loginActiveProfile: null as string | null,
  reloginProfiles: [] as string[],
  currentProfile: null as string | null,
  expandedQuotaProfiles: [] as string[],
  route: "dashboard" as ShellRoute,
  locale: "en" as Locale,
  theme: "light" as ThemeId,
  showAccountDetail: resolveInitialShowAccountDetail(),
  switchRestartTargets: resolveInitialSwitchRestartTargets() as SwitchRestartTargets,
  closeBehavior: resolveInitialCloseBehavior() as CloseBehavior,
  pageSize: 8,
  snapshot: null as ProfilesSnapshotResponse | null,
  currentQuota: null as QuotaSummary | null,
  usageStats: null as UsageStatsResponse | null,
  usageStatsProfile: null as string | null,
  usageStatsRange: resolveInitialUsageStatsRange() as UsageStatsRangePreset,
  usageStatsCustomStartAt: initialUsageStatsCustomRange.startAt as number | null,
  usageStatsCustomEndAt: initialUsageStatsCustomRange.endAt as number | null,
  usageStatsRefreshSeconds: resolveInitialUsageStatsRefreshSeconds() as UsageStatsRefreshSeconds,
  historyStats: null as UsageStatsResponse | null,
  historyStatsProfile: null as string | null,
  historyStatsRange: "today" as "today" | "7d" | "30d",
  codexSessions: [] as CodexSessionMeta[],
  selectedCodexSessionPath: null as string | null,
  codexSessionMessages: [] as CodexSessionMessage[],
  codexSessionMessageCache: {} as Record<string, CodexSessionMessage[]>,
  sessionMessagesLoading: false,
  sessionSearch: "",
  sessionVisibleCount: 60,
  sessionMessageVisibleCount: 40,
  expandedSessionMessages: [] as string[],
  settingsUsageProfile: null as string | null,
  usageSettingsByProfile: {} as Record<string, UsageQuerySettings>,
  codexSkills: [] as CodexSkillEntry[],
  selectedCodexSkillId: null as string | null,
  codexSkillsLoading: false,
  codexPrompts: [] as CodexPromptEntry[],
  selectedCodexPromptId: null as string | null,
  codexPromptsLoading: false,
};
